export const EVENTS = [
  {
    id: 1,
    title: 'Royal Garba Night',
    city: 'Ahmedabad',
    state: 'Gujarat',
    category: 'Culture',
    date: '18 Oct 2026',
    price: 799,
    rating: 4.9,
    bookings: 2840,
    capacity: 3500,
    crowd: 81,
    duration: '5 hours',
    host: 'Rang Gujarat Experiences',
    verified: true,
    image: 'https://images.unsplash.com/photo-1604608672516-f1b9b1d37076?auto=format&fit=crop&w=1200&q=85',
    description: 'A large community Garba celebration with live folk music, traditional décor, food stalls and hosted cultural activities.',
    highlights: ['Live folk orchestra', 'Traditional dress zone', 'Local food court', 'Verified organizer'],
  },
  {
    id: 2,
    title: 'Old City Heritage Walk',
    city: 'Jaipur',
    state: 'Rajasthan',
    category: 'Heritage',
    date: 'Every Weekend',
    price: 499,
    rating: 4.8,
    bookings: 1640,
    capacity: 25,
    crowd: 54,
    duration: '3 hours',
    host: 'Pink City Trails',
    verified: true,
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=85',
    description: 'Walk through Jaipur’s historic streets with a local storyteller, architecture stops, markets and traditional snack tasting.',
    highlights: ['Small groups', 'Local storyteller', 'Market trail', 'Photo stops'],
  },
  {
    id: 3,
    title: 'Private Farm Stargazing',
    city: 'Kutch',
    state: 'Gujarat',
    category: 'Nature',
    date: '24 Oct 2026',
    price: 1299,
    rating: 4.7,
    bookings: 930,
    capacity: 40,
    crowd: 28,
    duration: '1 night',
    host: 'Desert Sky Retreat',
    verified: true,
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=85',
    description: 'A quiet private-land experience with sunset tea, rural dinner, guided stargazing and a low-light camping area.',
    highlights: ['Low crowd', 'Private land', 'Dinner included', 'Night-sky guide'],
  },
  {
    id: 4,
    title: 'Konkan Coastal Road Trip',
    city: 'Ratnagiri',
    state: 'Maharashtra',
    category: 'Road Trip',
    date: '7 Nov 2026',
    price: 3499,
    rating: 4.9,
    bookings: 1245,
    capacity: 18,
    crowd: 42,
    duration: '2 days',
    host: 'Coastline Collective',
    verified: true,
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=85',
    description: 'A hosted coastal drive connecting beaches, viewpoints, village food and lesser-known local stops across the Konkan belt.',
    highlights: ['Curated route', 'Small group', 'Village food', 'Scenic stops'],
  },
  {
    id: 5,
    title: 'Himalayan Village Food Day',
    city: 'Manali',
    state: 'Himachal Pradesh',
    category: 'Food',
    date: 'Daily',
    price: 899,
    rating: 4.6,
    bookings: 760,
    capacity: 20,
    crowd: 35,
    duration: '6 hours',
    host: 'Mountain Table',
    verified: true,
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=85',
    description: 'A hosted day with village cooking, local produce, short walks and a traditional meal prepared with a local family.',
    highlights: ['Home-style meal', 'Local produce', 'Village walk', 'Small group'],
  },
  {
    id: 6,
    title: 'Fort Cycling Sunrise',
    city: 'Udaipur',
    state: 'Rajasthan',
    category: 'Adventure',
    date: 'Every Sunday',
    price: 699,
    rating: 4.8,
    bookings: 1120,
    capacity: 16,
    crowd: 47,
    duration: '4 hours',
    host: 'Ride Rajasthan',
    verified: true,
    image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1200&q=85',
    description: 'An early-morning guided cycling route around lakes, historic walls and viewpoints with breakfast at the finish.',
    highlights: ['Cycle included', 'Sunrise route', 'Breakfast', 'Guide support'],
  },
];

export const DESTINATIONS = [
  { name: 'Ahmedabad', tag: 'Culture & Food', crowd: 'Moderate', score: 72 },
  { name: 'Jaipur', tag: 'Heritage', crowd: 'Busy', score: 84 },
  { name: 'Kutch', tag: 'Nature & Culture', crowd: 'Calm', score: 34 },
  { name: 'Udaipur', tag: 'Lakes & Heritage', crowd: 'Moderate', score: 63 },
];

export const NEARBY = {
  hotels: [
    { name: 'Heritage Stay', meta: '4.6 · 1.2 km', price: '₹2,800/night' },
    { name: 'City Comfort Inn', meta: '4.4 · 2.1 km', price: '₹1,950/night' },
    { name: 'Premium Residency', meta: '4.8 · 3.0 km', price: '₹4,600/night' },
  ],
  food: [
    { name: 'Local Thali House', meta: '4.7 · Gujarati', price: '₹350/person' },
    { name: 'Street Food Trail', meta: '4.6 · Local', price: '₹250/person' },
    { name: 'Courtyard Café', meta: '4.5 · Multi-cuisine', price: '₹500/person' },
  ],
  transport: [
    { name: 'Airport Cab', meta: '35–50 min', price: 'From ₹650' },
    { name: 'Local Cab 8 hrs', meta: '80 km included', price: 'From ₹1,900' },
    { name: 'Auto / Local Ride', meta: 'On-demand', price: 'From ₹80' },
  ],
};
